const ASTRONOMY_FACTS: string[] = [
  'Un día en Venus dura más que un año en Venus.',
  'La Vía Láctea contiene entre 100 y 400 mil millones de estrellas.',
  'La luz del Sol tarda unos 8 minutos en llegar a la Tierra.',
  'Saturno es menos denso que el agua, así que en teoría podría flotar.',
  'Hay más estrellas en el universo observable que granos de arena en la Tierra.',
  'La Estrella Polar cambia con el tiempo debido a la precesión del eje terrestre.',
  'Júpiter tiene al menos 95 lunas conocidas.',
  'El Sol concentra el 99.8% de la masa de todo el sistema solar.',
  'Sin atmósfera, el cielo se ve negro incluso de día, como en la Luna.',
  'Una cucharadita de materia de una estrella de neutrones pesaría miles de millones de toneladas.',
  'La Vía Láctea y Andrómeda se fusionarán en unos 4,500 millones de años.',
  'El Monte Olimpo, en Marte, es el volcán más alto del sistema solar.',
  'Los anillos de Saturno están formados principalmente por hielo y roca.',
  'Una estrella fugaz es en realidad un meteoro quemándose en la atmósfera.',
  'El universo observable tiene un diámetro aproximado de 93 mil millones de años luz.',
  'La Luna se aleja de la Tierra unos 3.8 centímetros cada año.',
  'Se han detectado exoplanetas que podrían estar compuestos en gran parte por carbono cristalizado.',
  'En el centro de la Vía Láctea hay un agujero negro supermasivo llamado Sagitario A*.',
  'Un año en Neptuno equivale a unos 165 años terrestres.',
  'Las auroras ocurren cuando partículas del viento solar chocan con la atmósfera terrestre.',
  'Venus es el planeta más caliente del sistema solar, más que Mercurio.',
  'La Nebulosa del Cangrejo es el remanente de una supernova observada en el año 1054.',
  'El telescopio espacial Hubble lleva operando desde 1990.',
  'Un año luz equivale a unos 9.46 billones de kilómetros.',
  'La superficie visible del Sol tiene una temperatura de unos 5,500 °C.',
  'Plutón tarda 248 años terrestres en completar una órbita alrededor del Sol.',
  'Algunas estrellas de neutrones giran cientos de veces por segundo.',
  'En cielos muy oscuros, la galaxia de Andrómeda puede verse a simple vista.',
  'El primer exoplaneta orbitando una estrella similar al Sol se confirmó en 1995.',
  'La Tierra es el único planeta conocido con placas tectónicas activas.',
  'La sonda Voyager 1 es el objeto construido por humanos más alejado de la Tierra.',
  'Cerca de un agujero negro, el tiempo transcurre más lento que lejos de él.',
  'La cola de un cometa se forma por gas y polvo que se desprenden al acercarse al Sol.',
  'La constelación de Orión es visible desde casi cualquier punto habitado del planeta.',
  'El Big Bang describe la expansión del espacio, no una explosión dentro de él.',
  'Marte tiene dos lunas pequeñas, Fobos y Deimos, de forma irregular.',
  'El telescopio espacial James Webb observa principalmente en luz infrarroja.',
  'Una supernova puede brillar, por un tiempo, más que toda su galaxia.',
  'Mercurio casi no tiene atmósfera, por lo que su temperatura varía muchísimo entre el día y la noche.',
  'El Sol tarda unos 230 millones de años en completar una vuelta alrededor del centro de la Vía Láctea.',
  'Los cráteres de la Luna se conservan casi intactos porque no hay viento ni agua que los erosione.',
  'Las Nubes de Magallanes son galaxias enanas que orbitan la Vía Láctea.',
  'La luz que vemos de muchas estrellas partió de ellas hace cientos o miles de años.',
  'Un cuásar es el núcleo extremadamente brillante de una galaxia con un agujero negro activo.',
  'Titán, la luna más grande de Saturno, tiene lagos de metano líquido en su superficie.',
  'La materia oscura no emite luz, pero se detecta por su efecto gravitacional.',
  'El cinturón de asteroides se encuentra principalmente entre las órbitas de Marte y Júpiter.',
  'Europa, una luna de Júpiter, podría tener un océano de agua líquida bajo su capa de hielo.',
  'La primera fotografía real de un agujero negro se publicó en 2019.',
  'Un eclipse solar total ocurre cuando la Luna cubre completamente el disco del Sol visto desde la Tierra.',
  'La estrella más cercana al Sol, Próxima Centauri, está a poco más de 4 años luz de distancia.',
];

const MOOD_FACTS: string[] = [
  'Nombrar una emoción con precisión puede ayudar a regularla; a esto se le llama "etiquetado afectivo".',
  'Las emociones básicas suelen incluir alegría, tristeza, miedo, enojo, sorpresa y asco.',
  'El cerebro no distingue del todo entre una amenaza real y una imaginada al generar ansiedad.',
  'Llevar un registro de estados de ánimo puede ayudar a identificar patrones a lo largo del tiempo.',
  'La amígdala cerebral juega un papel clave en el procesamiento del miedo.',
  'Sonreír, incluso de forma un poco forzada, puede tener un pequeño efecto en cómo nos sentimos.',
  'El sueño insuficiente afecta directamente la regulación emocional al día siguiente.',
  'Las emociones suelen durar entre segundos y minutos; los estados de ánimo pueden durar horas o días.',
  'La respiración lenta y profunda puede activar el sistema nervioso parasimpático y reducir la sensación de estrés.',
  'El ejercicio regular está asociado con una mejora en el estado de ánimo a mediano plazo.',
  'La exposición a la luz solar puede influir en los ritmos circadianos y el ánimo.',
  'Hablar sobre lo que sentimos con alguien de confianza puede reducir la intensidad de una emoción difícil.',
  'Las emociones "negativas" también cumplen una función: el miedo nos protege, la tristeza nos hace bajar el ritmo.',
  'La palabra "ansiedad" viene del latín "anxietas", que significa angustia o aflicción.',
  'El cerebro sigue formando nuevas conexiones neuronales durante toda la vida, un proceso llamado neuroplasticidad.',
  'Las emociones se pueden contagiar socialmente; esto se conoce como "contagio emocional".',
  'Escribir sobre las propias emociones se ha asociado con beneficios para el bienestar psicológico.',
  'El estrés crónico puede afectar la memoria y la concentración a corto plazo.',
  'Practicar la gratitud de forma regular se ha vinculado con mayor bienestar subjetivo.',
  'No todas las culturas expresan las emociones de la misma manera, aunque las básicas parecen ser universales.',
  'El término "inteligencia emocional" fue popularizado por el psicólogo Daniel Goleman en los años 90.',
  'Las expresiones faciales de emociones básicas son reconocibles entre culturas muy distintas.',
  'La conexión social es uno de los factores más consistentemente vinculados al bienestar a largo plazo.',
  'El cerebro humano representa cerca del 2% del peso corporal, pero consume un 20% de la energía del cuerpo.',
  'Los recuerdos emocionales tienden a ser más vívidos que los recuerdos neutros.',
  'La meditación de atención plena se ha estudiado por su efecto en la reducción de síntomas de estrés.',
  'Reconocer una emoción no significa dejarse dominar por ella; son procesos distintos.',
  'El humor y la risa pueden reducir temporalmente los niveles de cortisol, la hormona del estrés.',
  'Pasar tiempo en la naturaleza se ha asociado con una reducción en la rumiación mental.',
  'Las emociones tienen componentes fisiológicos: el corazón, la respiración y la piel también "sienten".',
  'La palabra "emoción" viene del latín "emovere", que significa "mover hacia afuera".',
  'El bienestar psicológico no significa ausencia de emociones difíciles, sino la capacidad de transitarlas.',
  'Los patrones de sueño irregulares se han relacionado con mayor variabilidad en el estado de ánimo.',
  'Cultivar rutinas pequeñas y constantes puede dar una sensación de estabilidad emocional.',
  'El aislamiento social prolongado puede tener efectos comparables a otros factores de riesgo para la salud.',
  'Las emociones mixtas, como sentir alegría y tristeza al mismo tiempo, son psicológicamente normales.',
  'Pedir ayuda profesional cuando algo pesa demasiado es un acto de autocuidado, no una debilidad.',
  'La curiosidad, además de la felicidad, es considerada una emoción positiva por muchos psicólogos.',
  'Los bebés empiezan a reconocer expresiones emocionales básicas desde los primeros meses de vida.',
  'El término "resiliencia" describe la capacidad de adaptarse positivamente ante la adversidad.',
  'La música puede influir de forma medible en el estado de ánimo y la actividad cerebral.',
  'Diferentes emociones pueden activar patrones distintos de tensión muscular en el cuerpo.',
  'El optimismo aprendido es un concepto estudiado en psicología positiva, popularizado por Martin Seligman.',
  'Las emociones cumplen una función comunicativa: avisan a otros, y a nosotros mismos, qué está pasando.',
  'Tomarse pausas breves durante el día puede ayudar a evitar la acumulación de estrés.',
  'La autocompasión —tratarse con la misma amabilidad que a un amigo— es un área activa de investigación en psicología.',
  'El estado de ánimo puede influir en cómo interpretamos eventos neutros del día a día.',
  'Practicar la respiración diafragmática puede reducir la frecuencia cardíaca en pocos minutos.',
  'Las mascotas y los animales de compañía se han asociado con beneficios para el bienestar emocional de sus dueños.',
  'Reconocer los propios límites emocionales es parte fundamental de un buen autocuidado.',
];

const CURIOSITY_FACTS: string[] = [...ASTRONOMY_FACTS, ...MOOD_FACTS];

export function getRandomCuriosityFact(): string {
  return CURIOSITY_FACTS[Math.floor(Math.random() * CURIOSITY_FACTS.length)];
}